### ISSUE TITLE
General Question on Classification

### ISSUE THREAD

**Issue by dmatthewsbnd251** [Snorby/snorby#175]
I am experimenting with different snort guis at the moment.  I really like Snorby so far and the real plus is the ability to classify.  When using the demo I am able to classify events as false positive, however, they still show up in the queue.  What makes events disappear from the queue? Will events marked as false positives still show up as events in other graphs? My preference would of course make it so that events classified as false positives don't really show up in the queue again, in any graphs, and pretty much just live in the false positive configuration for reference/editing when and if needed.

I know my question is not exactly straight forward but could someone help me understand the expected behavior of classification and how that impacts other areas of this tool.

**Comment by GitHubEmail** [comment]
I just wanted to give my vote for this feature as well. That is, once an event has been classified by the user, it'd be great if Snorby could automatically classify that same event for all future occurrences.

Here are a few similar requests, though they are currently closed:

Classification of future events
https://github.com/Snorby/snorby/issues/68

Feature Request: Automatic classification of events by destination IP address
https://github.com/Snorby/snorby/issues/124

Thanks.
