### ISSUE TITLE
Settings Option to Disable Gravatar

### ISSUE THREAD

**Issue by dsn** [Snorby/snorby#227]
A change made at gravatar.com is preventing default avatars from loading. 

Your default image must now be "publicly accessible". See  https://twitter.com/beaulebens/statuses/251407787341524992

My IDS is behind a firewall and is not publicly accessible by the internet for security purposes, this makes the gravatar feature fail and return 500 errors calling gravatar which redirects you to i0.wp.com

Response from remote server: We cannot complete this request, remote data could not be fetched

If we could add an option to "Enable Gravatar Support" in the settings page users behind a firewall could disable this and not wait for a remote server to timeout and return errors to render the page or throw errors.

**Comment by superwanglin** [comment]
Some how this option got removed in a7629d720ee25177af86304d9e8f522d0eece68f. Why?
