### ISSUE TITLE
snorby and postgres 

### ISSUE THREAD

**Issue by micromachine** [Snorby/snorby#265]
Hi all, 
I have separated instance of snorby and separate postgres database. 
All variables in database config looks correctly. 
When we start  :  bundle exec rake snorby:setup --trace

*\* Invoke snorby:setup (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
*\* Execute snorby:setup
*\* Invoke secret (first_time)
*\* Execute secret
6b0f50f642cf42a29093883aaa7c7a1901038d7052cbe5baa25e44a6346114c78a0ebe137e059c1dcfddc064c570515aa5718fa3c6ec04082dda81b2141bea95
*\* Invoke db:create (first_time)
*\* Invoke environment 
*\* Execute db:create
createdb: nie można połączyć się do bazy danych postgres: nie można połączyć się z serwerem: Nie ma takiego pliku ani katalogu
    Czy serwer działa lokalnie i akceptuje
    połączenia przy pomocy gniazd dziedziny Uniksa "/tmp/.s.PGSQL.5432"?

In config we have remote database server, why application want connect to 
localhost  ?

*\* Invoke snorby:update (first_time)
*\* Invoke environment 
*\* Execute snorby:update
*\* Invoke db:autoupgrade (first_time)
*\* Invoke environment 
*\* Execute db:autoupgrade
[datamapper] Finished auto_upgrade! for :default repository 'sagandb'
*\* Invoke db:seed (first_time)
*\* Invoke environment 
*\* Execute db:seed
rake aborted!
BŁĄD:  relacja "information_schema.statistics" nie istnieje
LINE 2:           select \* FROM information_schema.statistics 
                                ^
In this case information_schema.statistics is in mysql... but we use postgres. 

What is wrong  ?

micro

**Comment by Drewshg312** [comment]
Any news on postgres support?
