### ISSUE TITLE
[Snorby 2.6.2] cannot load such file -- dm-rails/railtie

### ISSUE THREAD

**Issue by TheLight29** [Snorby/snorby#305]
Hi all !

I try to install Snorby on ArchLinux based to an ARM processor.

I have already installed Ruby 1.9.3, ImageMagick and Wkhtmltopdf. The command "bundle install" install last release of Rails.

But when I run "rake snorby:setup", I have the following error : "cannot load such file -- dm-rails/railtie".

What should I do ? Am I missed something ?

Thanks for your help ! :-)

**Comment by mandrake74** [comment]
Well for me reinstalling from source was not enough to fix it, I also needed to install dm-rails and bundler in 1.2.1 version, see https://github.com/Snorby/snorby/issues/355
But the link provided above was useful to fix annoying yaml messages ;-)
