### ISSUE TITLE
Snorby with SSL connection

### ISSUE THREAD

**Issue by deskanmond** [Snorby/snorby#353]
Hello,

I am trying to setup Snorby with SSL as well.

I have installed Phusion Passenger on Apache and I have my SSL certification installed to apache.

I have tested apache with SSL and it's working properly but for some reason, my snorby won't run at all. Below is what I got from the browser.

Secure Connection Failed

An error occurred during a connection to iris.firstnutri.com. SSL received a record that exceeded the maximum permissible length. (Error code: ssl_error_rx_record_too_long)

I believe I configured something wrong in the snorby config file.

Is there a straight forward instruction guide that I can follow to configure the snorby with SSL?

FYI - Snorby has been working great with regular port 3000.

thanks,
Desmond

**Comment by petiepooo** [comment]
There's some information at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/suricata_snorby_and_barnyard2_set_up_guide

I'd suggest also taking a look at how SecurityOnion has it setup.  They're also using Apache and Phusion Passenger, and use a self-signed key by default.

**Comment by miketanderson** [comment]
I'm more familiar with nginx, but this still appears to be more of an Apache and SSL question. 

The only related directive in snorby_config.yml is ssl: true, but that is for reports more than hosting the application. As long as your web server is set up correctly, snorby should just work.
