### ISSUE TITLE
undefined method `each' for nil:NilClass > on snorby:setup

### ISSUE THREAD

**Issue by Marco208** [Snorby/snorby#360]
Hi,

When I run:

    RAILS_ENV=production bundle exec rake snorby:setup --trace

the following output will be returned:

    /usr/local/lib/ruby/1.9.1/yaml.rb:84:in `<top (required)>':
    It seems your ruby installation is missing psych (for YAML output).
    To eliminate this warning, please install libyaml and reinstall your ruby.
    Jammit Warning: Asset compression disabled -- Java unavailable.
    No time_zone specified in snorby_config.yml; detected time_zone: America/New_York
    ** Invoke snorby:setup (first_time)
    ** Invoke environment (first_time)
    ** Execute environment
    rake aborted!
    undefined method `each' for nil:NilClass
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/dm-rails-1.2.1/lib/dm-rails/setup.rb:11:in `setup'
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/dm-rails-1.2.1/lib/dm-rails/railtie.rb:90:in `block in <class:Railtie>'
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/activesupport-3.1.12/lib/active_support/lazy_load_hooks.rb:34:in `call'
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/activesupport-3.1.12/lib/active_support/lazy_load_hooks.rb:34:in `execute_hook'
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/activesupport-3.1.12/lib/active_support/lazy_load_hooks.rb:43:in `block in run_load_hooks'
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/activesupport-3.1.12/lib/active_support/lazy_load_hooks.rb:42:in `each'
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/activesupport-3.1.12/lib/active_support/lazy_load_hooks.rb:42:in `run_load_hooks'
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/railties-3.1.12/lib/rails/application/finisher.rb:56:in `block in <module:Finisher>'
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/railties-3.1.12/lib/rails/initializable.rb:30:in `instance_exec'
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/railties-3.1.12/lib/rails/initializable.rb:30:in `run'
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/railties-3.1.12/lib/rails/initializable.rb:55:in `block in run_initializers'
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/railties-3.1.12/lib/rails/initializable.rb:54:in `each'
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/railties-3.1.12/lib/rails/initializable.rb:54:in `run_initializers'
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/railties-3.1.12/lib/rails/application.rb:96:in `initialize!'
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/railties-3.1.12/lib/rails/railtie/configurable.rb:30:in `method_missing'
    /root/snorby/config/environment.rb:3:in `<top (required)>'
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/activesupport-3.1.12/lib/active_support/dependencies.rb:240:in `require'
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/activesupport-3.1.12/lib/active_support/dependencies.rb:240:in `block in require'
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/activesupport-3.1.12/lib/active_support/dependencies.rb:223:in `block in load_dependency'
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/activesupport-3.1.12/lib/active_support/dependencies.rb:640:in `new_constants_in'
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/activesupport-3.1.12/lib/active_support/dependencies.rb:223:in `load_dependency'
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/activesupport-3.1.12/lib/active_support/dependencies.rb:240:in `require'
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/railties-3.1.12/lib/rails/application.rb:83:in `require_environment!'
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/railties-3.1.12/lib/rails/application.rb:203:in `block (2 levels) in initialize_tasks'
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:205:in `call'
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:205:in `block in execute'
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:200:in `each'
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:200:in `execute'
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
    /usr/local/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:176:in `block in invoke_prerequisites'
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:174:in `each'
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:174:in `invoke_prerequisites'
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:157:in `block in invoke_with_call_chain'
    /usr/local/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2/lib/rake/task.rb:144:in `invoke'
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:112:in `invoke_task'
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:90:in `block (2 levels) in top_level'
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:90:in `each'
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:90:in `block in top_level'
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:84:in `top_level'
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:62:in `block in run'
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:59:in `run'
    /root/snorby/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2/bin/rake:32:in `<top (required)>'
    /root/snorby/vendor/bundle/ruby/1.9.1/bin/rake:23:in `load'
    /root/snorby/vendor/bundle/ruby/1.9.1/bin/rake:23:in `<main>'
    Tasks: TOP => snorby:setup => environment

Will someone be able to help me in this case?

I'm running in the following envoirment:

* CentOS 7 64 bits
* ruby 1.9.3p551 (2014-11-13) [x86_64-linux]
* Rails 3.1.12

Config files:

**database.yml**

    snorby: &snorby
      adapter: mysql
      username: root
      password: "Password!1"
      host: localhost

**snorby_config.yml**

    production:
      domain: 'snorby.testdomain.nl'
      mailer_sender: 'snorby@snorby.org'
      wkhtmltopdf: /usr/local/bin/wkhtmltopdf
      rules:
        - "/etc/snort/rules"
        - "/etc/snort/so_rules"

Thanks in advance

**Comment by jakubek** [comment]
You should add these lines to your database.yml and then try: bundle exec rake snorby:setup --trace
```
development:
  database: snorby
  <<: *snorby

test:
  database: snorby
  <<: *snorby

production:
  database: snorby
  <<: *snorby
```
