### ISSUE TITLE
SSL connection to MySQL

### ISSUE THREAD

**Issue by afiaux** [Snorby/snorby#368]
Hello,

Can snorby connect to a remote MySQL server using SSL? If yes, how can I provide the client certificate, key and CA certificate? If no, is it a planned feature for a future release?

Thank you in advance,

**Comment by mephux** [comment]
http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/MysqlAdapter.html

*Dustin Willis Webber*

**Comment by afiaux** [comment]
Thanks a lot for your quick reply. I've never done any ruby on rails so I'm probably doing it wrong. I've added these parameters in the `config/database.yml` file like this:
```
snorby: &snorby
  adapter: mysql
  username: snorby
  password: "password"
  host: 10.0.1.1
  sslca: /etc/snorby/ca.crt
  sslkey: /etc/snorby/snorby.key
  sslcert: /etc/snorby/snorby.crt
```
Unfortunately the connection never uses SSL, if I force SSL for the snorby database with:
```
GRANT USAGE ON snorby.* TO 'snorby'@'10.0.1.2' REQUIRE SSL;
```
I get the following error:
```
Started GET "/dashboard" for 10.0.1.128 at 2015-03-30 14:47:30 +0200
  Processing by PageController#dashboard as HTML
Access denied for user 'snorby'@'10.0.1.2' (using password: YES) (code: 1045, sql state: 28000, query: , uri: )
Completed 500 Internal Server Error in 7ms

DataObjects::ConnectionError (Access denied for user 'snorby'@'10.0.1.2' (using password: YES)):
  app/controllers/application_controller.rb:37:in `user_setup'
```
However the connection is working perfectly fine using the MySQL client (from the snorby machine):
```
mysql -h10.0.1.1 -usnorby -ppassword --ssl-ca=/etc/snorby/ca.crt --ssl-key=/etc/snorby/snorby.key --ssl-cert=/etc/snorby/snorby.crt snorby
```
I've also tried adding the `sslcapath` and `sslcipher` but the result was the same.

Am I doing something wrong? Should the SSL parameters be defined somewhere else than in `config/database.yml`?

Thank you in advance for your help.

**Comment by gehrhorn** [comment]
@afiaux are you sure the password in `config/database.yml` should be in quotes?

**Comment by afiaux** [comment]
Thank you for your reply. I've tested without the quotes and unfortunately the result is the same.

**Comment by afiaux** [comment]
I've finally managed to fix this issue, the problem was with the way I specified the SSL parameters in the `config/database.yml` file.

```
snorby: &snorby
  adapter: mysql
  username: 'snorby'
  password: 'password'
  host: '10.0.1.1'
  ssl: {
    ca_cert: '/etc/snorby/ca.crt',
    client_key: '/etc/snorby/snorby.key',
    client_cert: '/etc/snorby/snorby.crt'
  }
```

**Comment by miketanderson** [comment]
Great! Glad that you fixed it. Thanks for following up with the solution. Marking this as closed.
