### ISSUE TITLE
Timestamp frozen events snorby

### ISSUE THREAD

**Issue by Fl0r1d** [Snorby/snorby#370]
Hi, guys

I have been getting an issue with timestamp on barnyard events, events are being logged correctly in mysql database snorby only the time of the event is not updated.

Barnyard2
Version 2.1.14 (Build 336)

-*> Snort! <*-
  o"  )~   Version 2.9.2.2 IPv6 GRE (Build 121) 

MYSQL
>use snorby;
>select timestamp from event;
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |
| 2015-05-25 13:35:59 |

Regards!

**Comment by miketanderson** [comment]
Have you verified the source data? This strongly looks like it has nothing to do with snorby and everything to do with either barnyard, snort or the system you installed them on. You should be able to inspect the unified2 output with u2spewfoo

**Comment by Fl0r1d** [comment]
Thanks mike for your advice

I did it. I figured out event and packet second are not changing correctly.

Packet
	sensor id: 0	event id: 1	event second: 1432741433
	packet second: 1432741433	packet microsecond: 503554
	linktype: 1	packet_length: 106

....

Packet
	sensor id: 0	event id: 61	event second: 1432741434
	packet second: 1432741434	packet microsecond: 2321
	linktype: 1	packet_length: 98
....

Packet
	sensor id: 0	event id: 215	event second: 1432741435
	packet second: 1432741435	packet microsecond: 8982
	linktype: 1	packet_length: 98
....

I think this is a barnyard issue but I am not pretty sure. Any ideas?

My based system is:

Linux test 3.7-trunk-686-pae #1 SMP Debian 3.7.2-0+kali8 i686 GNU/Linux

Regards!

**Comment by miketanderson** [comment]
I'm not an expert in either barnyard or snort, but you can open an issue with barnyard  [https://github.com/firnsy/barnyard2/issues](https://github.com/firnsy/barnyard2/issues) on git or with snort [https://www.snort.org/community](https://www.snort.org/community) through their mailing list or through their community support groups.

Personally I would look through the barnyard output with u2spewfoo and see if the same single digit increments exists in that output. If it does then it is likely a snort issue, if it looks correct in that output it is probably a barnyard issue.

**Comment by Fl0r1d** [comment]
I think I will go to ask them how to solve it as you said.

Thanks for helping.
