### ISSUE TITLE
Wrong date in "Last 24" tab?

### ISSUE THREAD

**Issue by mindph** [Snorby/snorby#371]
Hello. For some reason, the "Last 24" tab in Snorby does show a wrong date. It supposed to be a timeframe of the last 24h, right? But it are not 24h it are 0 minutes, see screenshot
![screenshot_2015-06-01_10-43-28](https://cloud.githubusercontent.com/assets/12167035/7909361/e096f256-084b-11e5-9320-cd650e1417e3.png)

**Comment by miketanderson** [comment]
You are absolutely correct. This is a relatively easy fix in page_helper.rb. I'll see about making a pull request and asking @gehrhorn to merge it.

**Comment by miketanderson** [comment]
This should be resolved in the current codebase. This issue can be closed. 

Thanks for the assist @gehrhorn!

**Comment by gehrhorn** [comment]
Closing per @miketanderson. @mindph reopen if things go poorly.
