### ISSUE TITLE
Error in _signature.html.erb

### ISSUE THREAD

**Issue by zhiweilou** [Snorby/snorby#373]
There is an error in snorby/app/views/events/_signature.html.erb. In line 27,  "baseuri + " should be deleted. Otherwise, the url of "View all " in results page will be : http://hostname:3000/baseuri, which is a 404 page.
The  version  is Snorby 2.6.2.

**Comment by gehrhorn** [comment]
Hi @zhiweilou, can you turn this into a pull request?

**Comment by zhiweilou** [comment]
Ok. I will do that tomorrow.

Date: Wed, 3 Jun 2015 07:27:46 -0700

**Comment by gehrhorn** [comment]
Merged.
