### ISSUE TITLE
Stored Cross-Site Scripting (XSS) Vulnerability

### ISSUE THREAD

**Issue by eurialo** [Snorby/snorby#377]
Latest version of snorby is vulnerable to cross-site scripting attack.
These are the steps to reproduce the bug:

1) Start **Snorby** in production-mode and log in the **web UI**.
2) Go to '**Administration**' -> '**Classifications**' and '**Add classification**'.
3) In the title of classification just add the xss vector: title**">&lt;img src=x onerror=alert(document.cookie)>**
4) Come back to dashboard and click to '**My Queue**' and see the alert.

The output from the page **snorby/app/views/events/_menu.html.erb** is not properly sanitized before its rendering:

<pre>
<% @classifications.each do |cls| %>
	<% if cls.locked && cls.hotkey %>
		<%= drop_down_item "#{cls.name}<span class='shortcut'>#{cls.shortcut}</span>", '#', nil, { :class => 'classification', :"data-classification-id" => cls.id.to_i } %>
	<% else %>
		<%= drop_down_item "#{cls.name}", '#', nil, { :class => 'classification', :"data-classification-id" => cls.id.to_i } %>
	<% end %>
<% end %>
</pre>

A simple **XSS mitigation** on rails could be the usage of the **sanitize**, for example the code below filters the xss vector by removing the onerror attribute from the image tag:

<pre>
<% @classifications.each do |cls| %>
	<% if cls.locked && cls.hotkey %>
		<%= drop_down_item "#{sanitize cls.name}<span class='shortcut'>#{cls.shortcut}</span>", '#', nil, { :class => 'classification', :"data-classification-id" => cls.id.to_i } %>
	<% else %>
		<%= drop_down_item "#{sanitize cls.name}", '#', nil, { :class => 'classification', :"data-classification-id" => cls.id.to_i } %>
	<% end %>
<% end %>
</pre>

This is a demonstartion screenshot:

![snorby-xss](https://cloud.githubusercontent.com/assets/1346701/8420963/fde45338-1ec8-11e5-84d8-496819ef1ede.png)
![snorby-render-xss](https://cloud.githubusercontent.com/assets/1346701/8421277/c0fad010-1ecc-11e5-825d-fdac4c3d58e7.png)

**Comment by miketanderson** [comment]
Thanks for the detailed report. I confirmed this was a problem and pushed a fix.

**Comment by eurialo** [comment]
You're welcome! 
I have requested a CVE-id for this issue ok?
