### ISSUE TITLE
snorby.org is domain parked / broken - makes project look dodgy

### ISSUE THREAD

**Issue by sammcj** [Snorby/snorby#391]
![screen shot 2015-09-02 at 11 51 24 am](https://cloud.githubusercontent.com/assets/862951/9621374/f9121caa-5168-11e5-87a5-8c6991879640.jpg)

**Comment by hostingnuggets** [comment]
:-1:

**Comment by gehrhorn** [comment]
Where are you seeing references to snorby.org in the code?

**Comment by gehrhorn** [comment]
I changed it on the wiki. Trying to figure out how to become a channel op on the IRC channel to change the topic.
