### ISSUE TITLE
Directory listing instead of Snorby web interface

### ISSUE THREAD

**Issue by Drewshg312** [Snorby/snorby#394]
Hi!
I'm using Apache 2.4.17 and Passenger 5.0.21 under OS X 10.10.5
Apache virtual host for Snorby:

```
<VirtualHost *:8443>
    ServerAdmin admin@server.snorby
    ServerName www.server.snorby
    ServerAlias server.snorby
    ErrorLog /usr/local/var/log/apache2/snorby_error.log
    LogLevel warn
    CustomLog /usr/local/var/log/apache2/snorby_access.log combined
    DocumentRoot /usr/local/var/www/snorby/public
    <Directory "/usr/local/var/www/snorby/public">
        Options Indexes FollowSymLinks Includes ExecCGI
        #Require all granted
        Order deny,allow
        Allow from all
        Options -MultiViews
    </Directory>
    ###-- SSL Certificates --###
    SSLEngine on
    SSLCertificateFile "/usr/local/etc/apache2/2.4/ssl-keys/ssl_server.crt"
    SSLCertificateKeyFile "/usr/local/etc/apache2/2.4/ssl-keys/ssl_server.key"
    SetEnvIf User-Agent ".*MSIE.*" nokeepalive ssl-unclean-shutdown
    CustomLog /usr/local/var/log/apache2/snorby_ssl_request.log \
    "%t %h %{SSL_PROTOCOL}x %{SSL_CIPHER}x \"%r\" %b"
</VirtualHost>
```

I've included the **passenger.conf** into my **httpd.conf**:

```
LoadModule passenger_module /usr/local/opt/passenger/libexec/buildout/apache2/mod_passenger.so
PassengerRoot /usr/local/opt/passenger/libexec/src/ruby_supportlib/phusion_passenger/locations.ini
PassengerDefaultRuby /usr/local/var/rbenv/shims/ruby
    #PassengerDefaultRuby /usr/local/var/rbenv/versions/1.9.3-p551/bin/ruby
PassengerResolveSymlinksInDocumentRoot on
PassengerLogLevel 3
```

But after restart of httpd and navigating `https://server.snorby` getting the directory listing instead of Snorby web interface:

![1](https://cloud.githubusercontent.com/assets/10493450/10777536/cf3bb1c4-7cd9-11e5-9190-754176761ad0.jpg)

Please help!

Thank you!

**Comment by mindph** [comment]
Hello. I have got the same problem. When I go to http://vhost/dashboard I see snorby, but vhost/ gives me just the ./public directory listing that's configured in the vhost

This happened after a recent upgrade of Debian stretch/sid

**Comment by Drewshg312** [comment]
It's been a while... I don't use snorby anymore. I've chosen SELKS as an IDPS solution with kibana as a front-end.

**Comment by Kruully** [comment]
Hi @Drewshg312 ,

I'm using SELKS too, but I want add to this IDPS solution an summary by email with Snorby.

Did you happen have the Snorby web interface instead of the directory? Before chose SELKS?

**Comment by Drewshg312** [comment]
Yes, it worked before. I run it on mac box, but then I've updated something (passenger I guess) and it stopped working since then. It was long time ago... Event viewer on SELKS seem a nice solution to me..

**Comment by Kruully** [comment]
Ok, thank you for your answer.

**Comment by Kruully** [comment]
I reinstall everything and it's works ! Youhou!!

I don't know what I did differently...
