### ISSUE TITLE
Snorby 2.6.3 - Cant login

### ISSUE THREAD

**Issue by TheBR** [Snorby/snorby#397]
Hi All,
  Fresh install of Snorby, i can get to the Snorby login page but it wont let me login, any attempt to use the default username and password 

snorby@snorby.org
snorby

And i get a response of "Error, Authentication Failed!"

Production.log shows the following:-

Started GET "/users/login" for 192.168.0.165 at 2015-11-04 11:37:46 +0000
  Processing by SessionsController#new as HTML
Rendered users/sessions/new.html.erb within layouts/login (5.6ms)
Rendered layouts/_version.html.erb (1.5ms)
Completed 200 OK in 51ms (Views: 49.6ms | Models: 0.000ms)

Started POST "/users/login" for 192.168.0.165 at 2015-11-04 11:37:59 +0000
  Processing by SessionsController#create as */*
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"X46QmmlgF/m+voRvFUJCv+pc7bZhbmgWrKA3TMfhu9o=", "user"=>{"email"=>"snorby@snorby.org", "password"=>"[FILTERED]", "remember_me"=>"1"}}
Completed 401 Unauthorized in 74ms
  Processing by SessionsController#failure as */*
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"X46QmmlgF/m+voRvFUJCv+pc7bZhbmgWrKA3TMfhu9o=", "user"=>{"email"=>"snorby@snorby.org", "password"=>"[FILTERED]", "remember_me"=>"1"}}
Completed 200 OK in 1ms (Views: 0.3ms | Models: 26.202ms)

Any ideas?

**Comment by panagioto** [comment]
The default credentiala are:
username: snorby@example.com
password: snorby

**Comment by TheBR** [comment]
NO ******* WAY! (Cries into keyboard)

You have no idea how long i've been trying to fix this. Everything i read said snorby@snorby.org

Thanks for pointing this out...
