### ISSUE TITLE
empty dashboard

### ISSUE THREAD

**Issue by mobidevadmin** [Snorby/snorby#401]
Hello,
I'm using suricata+barnyar2+snorby 2.6.3.
Even though events are collecting and sorting dashboard shows zeroes. Each "zero" redirects you to existing severity lists
https://gyazo.com/dbcf54c2213ef0559bf8a5bcc32a1f62

**Comment by brian-olson** [comment]
I've seen this a few times and it was always related to timezone issues. Ensure that your timezone is the same across all systems and/or modify the configurations to deal with the TZ differences.

**Comment by mobidevadmin** [comment]
Hello,

the issue isn't relevant already as the root of the problem was barnyard2 which performance was poor and he couldn't catch up the suricata. So Snorby was couple hours behind suricata log.
