### ISSUE TITLE
snorby.org is serving annoyware / possible malware

### ISSUE THREAD

**Issue by sbromberger** [Snorby/snorby#421]
Hi,

Not sure where to report this, but it appears that www[dot]snorby[dot]org is being redirected alternately to a parking page and a page that loads continuous popups with messages that suggest the computer has been infected.

Screenshot from Firefox below (note redirect URL).

<img width="1209" alt="screen shot 2016-02-16 at 14 00 07" src="https://cloud.githubusercontent.com/assets/941359/13089322/b5cad2d6-d4b5-11e5-8f66-f06df5be686e.png">

**Comment by sbromberger** [comment]
(the reason I posted this is because www[dot]snorby[dot]org is referenced in the #snorby Freenode IRC channel, which is itself referenced as a support resource in README. Nobody from the IRC channel has been active in the past couple of days.)

**Comment by sbromberger** [comment]
See also #391.

**Comment by gehrhorn** [comment]
Where are you seeing references to snorby.org in the code?

**Comment by sbromberger** [comment]
@gehrhorn README.md references the wiki, which has references to the "official website" and the IRC channel (https://github.com/Snorby/snorby/wiki).

**Comment by gehrhorn** [comment]
@sbromberger I changed it on the wiki. Trying to figure out how to become a channel op on the IRC channel to change the topic.

**Comment by sbromberger** [comment]
Thanks. I think that takes care of the most pressing issue. It's a shame that the domain got poached.
