### ISSUE TITLE
Unable to start snorby worker lib do_mysql.so missing

### ISSUE THREAD

**Issue by azgaviperr** [Snorby/snorby#450]
It's impossible to start the worker. 
It's seems that /opt/snorby/vendor/cache/ruby/2.1.0/gems/do_mysql-0.10.17/lib/do_mysql/do_mysql.so doesn't exist.

OS: Debian 8 x64
root@srv-snorby:/opt/snorby# bundle exec rake snorby:update
syck has been removed, psych is used instead
No time_zone specified in snorby_config.yml; detected time_zone: Europe/Paris
[datamapper] Finished auto_upgrade! for :default repository 'snorby'
- Removing old jobs
- Starting the Snorby worker process.
  /opt/snorby/vendor/cache/ruby/2.1.0/gems/do_mysql-0.10.17/lib/do_mysql.rb:29:in `require': incompatible library version - /opt/snorby/vendor/cache/ruby/2.1.0/gems/do_mysql-0.10.17/lib/do_mysql/do_mysql.so (LoadError)
  from /opt/snorby/vendor/cache/ruby/2.1.0/gems/do_mysql-0.10.17/lib/do_mysql.rb:29:in`<top (required)>'
  from /opt/snorby/vendor/cache/ruby/2.1.0/gems/dm-mysql-adapter-1.2.0/lib/dm-mysql-adapter/adapter.rb:1:in `require'
  from /opt/snorby/vendor/cache/ruby/2.1.0/gems/dm-mysql-adapter-1.2.0/lib/dm-mysql-adapter/adapter.rb:1:in`<top (required)>'
  from /opt/snorby/vendor/cache/ruby/2.1.0/gems/dm-mysql-adapter-1.2.0/lib/dm-mysql-adapter.rb:1:in `require'
  from /opt/snorby/vendor/cache/ruby/2.1.0/gems/dm-mysql-adapter-1.2.0/lib/dm-mysql-adapter.rb:1:in`<top (required)>'
  from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:76:in `require'
  from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:76:in`block (2 levels) in require'
  from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:72:in `each'
  from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:72:in`block in require'
  from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:61:in `each'
  from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:61:in`require'
  from /usr/lib/ruby/vendor_ruby/bundler.rb:133:in `require'
  from /opt/snorby/config/application.rb:12:in`<top (required)>'
  from /opt/snorby/config/environment.rb:2:in `require'
  from /opt/snorby/config/environment.rb:2:in`<top (required)>'
  from /opt/snorby/script/delayed_job:3:in `require'
  from /opt/snorby/script/delayed_job:3:in`<main>'
  [X] Error: Unable to start the Snorby worker process.

**Comment by lambis7** [comment]
You need to install this
`sudo apt-get install -y mysql-server libmysqlclient-dev mysql-client`

**Comment by gehrhorn** [comment]
@lambis7 solution should fix this.
