### ISSUE TITLE
Snorby requires Ruby <2 AND Byebug but byebug requires Ruby > 2

### ISSUE THREAD

**Issue by QuentinIUT** [Snorby/snorby#469]
All is in the title, the struggle to install Snorby is incredible... I'm in front of this problem, I've installed Ruby v1.9.3 and Rails v3.0.0 in order to make Snorby to run, but when trying "bundle install" command the bundler fails with error saying that Byebug requires Ruby > 2.

I've tried to install various versions of Byebug to install separately, all seems to require Ruby 2. What can I do to use Snorby ? What point am I missing ?

Currently connected to the IRC chan, more than 10 people in it but no reaction at all, where can I get help ?

**Comment by RobKillilea** [comment]
I have this exact issue and cannot get snorby running, unfortunately this issue was closed without a resolution being documented, can anyone shed some light on how to reconcile a Ruby version <2 with a Byebug gem that does not seem to exist at any version to work with Ruby <2 ...

**Comment by QuentinIUT** [comment]
@RobKillilea Snorby is working well with Ruby 2.3.0, that's how I finally get it to work. But even after that, there is plenty of gems that are no more supported and not working with each other. So I advise you to give up with Snort and Snorby here. All products around Snort are outdated and abandonned, while the community and diversity around Suricata is skyrocketing.

In case you have some time to lose, I can give you (here as an attached file) an installation guide for Snorby on CentOS 7, as I finally succeded to get it work in order to build a test environnement. So I wrote this guide for the next team to work on this product after me. Please consider that the whole guide is written in french, but all commands used are explicitely given, so you might be able to go through it, with a little bit help from Google Trad or so.
[guide_install_snorby.pdf](https://github.com/Snorby/snorby/files/1333185/guide_install_snorby.pdf)
