### ISSUE TITLE
installing on centos7

### ISSUE THREAD

**Issue by topeminent** [Snorby/snorby#473]
HI,
I m trying to install snorby on centos7 but i get this error at the bundle install part 
The gemspec at
/usr/local/rvm/gems/ruby-1.9.3-p551/bundler/gems/snorby_cas_authenticatable-281a58b36368/devise_cas_authenticatable.gemspec
is not valid. Please fix this gemspec.
The validation error was 'duplicate dependency on devise (>= 1.0.6), (>= 0) use:
    add_runtime_dependency 'devise', '>= 1.0.6', '>= 0'

I m a nooby regarding ruby. Any ideas how to fix this?
S.

**Comment by AquaL1te** [comment]
Same problem here... How did you fix it?
