### ISSUE TITLE
Anyone is running Snorby on Systemd?

### ISSUE THREAD

**Issue by nan008** [Snorby/snorby#474]
I am trying to run the Snorby as systemd  (without passenger/unicorn) but the scripts are not starting correctly

I can do bundle exec rails server -e development -b 0.0.0.0 on the command line while in snorby folder but when I put it in a script and execute with systemctl it is not working correctly.

```bash
WorkingDirectory=/tmp/snorby
Environment=RAILS_ENV=development
ExecStart=/usr/local/rbenv/shims/bundle exec rails server -d -b 0.0.0.0
```

Anyone solved it?

**Comment by nan008** [comment]
I managed it to work with systemctl command

**Comment by sec-u** [comment]
define the directory in cli

**Comment by nan008** [comment]
It does not help to define the directory in service file - it will fail with bundle exec command on systemd, you need to know what web app is running Snorby, I asked the question as I do not know Ruby and as I said I solved it

**Comment by Whasley** [comment]
nan008, What did you do to solve this problem?
