### ISSUE TITLE
undefined method `yaml_as' for DataMapper::Resource:Module (NoMethodError)

### ISSUE THREAD

**Issue by asnur** [Snorby/snorby#506]
please help me solve the problem with snorby when I install with the command 'RAIL_ENV = production bundle exec rake snorby: setup' and the output looks like this' undefined method `yaml_as' for DataMapper :: Resource: Module (NoMethodError) '

**Comment by saiqulhaq** [comment]
can you paste the full backtrace?

**Comment by CryptoMastersBitch** [comment]
Awww, Do you need help?

**Comment by rubensnorby** [comment]
/home/ruben/.rvm/gems/ruby-2.6.1/gems/activesupport-3.2.22/lib/active_support/core_ext/object/duplicable.rb:111: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
rake aborted!
NoMethodError: undefined method `yaml_as' for DataMapper::Resource:Module
/home/ruben/.rvm/gems/ruby-2.6.1/bundler/gems/delayed_job_data_mapper-6f1c4a8c3ad6/lib/delayed/serialization/data_mapper.rb:2:in `block in <top (required)>'
/home/ruben/.rvm/gems/ruby-2.6.1/bundler/gems/delayed_job_data_mapper-6f1c4a8c3ad6/lib/delayed/serialization/data_mapper.rb:1:in `class_eval'
/home/ruben/.rvm/gems/ruby-2.6.1/bundler/gems/delayed_job_data_mapper-6f1c4a8c3ad6/lib/delayed/serialization/data_mapper.rb:1:in `<top (required)>'
/home/ruben/.rvm/gems/ruby-2.6.1/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
/home/ruben/.rvm/gems/ruby-2.6.1/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `block in require'
/home/ruben/.rvm/gems/ruby-2.6.1/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/ruben/.rvm/gems/ruby-2.6.1/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
/home/ruben/.rvm/gems/ruby-2.6.1/bundler/gems/delayed_job_data_mapper-6f1c4a8c3ad6/lib/delayed_job_data_mapper.rb:5:in `<top (required)>'
/var/www/html/snorby/config/application.rb:12:in `<top (required)>'
/var/www/html/snorby/Rakefile:4:in `require'
/var/www/html/snorby/Rakefile:4:in `<top (required)>'
/home/ruben/.rvm/gems/ruby-2.6.1/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/home/ruben/.rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in `eval'
/home/ruben/.rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in `<main>'
(See full trace by running task with --trace)
