### ISSUE TITLE
License Issue: HighCharts (used on dashboard) is not GPLv3, nor can it be used with commercial or government websites.

### ISSUE THREAD

**Issue by shadowbq** [Snorby/snorby#70]
## Snorby contains highcharts which is non-gpl compliant. 

Use of snorby in a corporate, government, or for-profit is affected by these license restrictions.

Snorby comes with a price tag of a developer seat license (360 USD).

Snorby can not override the restrictions within the use of this code.

You are allowed to distribute Highcharts with non-commercial packages given that you fulfill two conditions:
- Emphasize to your users that Highcharts is not free for commercial use. You can do this on your download page or when your users activate Highcharts in your application

Snorby must correct the front page if we continue to use this javascript.

The snorby webpage states "Open Source Snorby is 100% free and open source (as in beer and speech) and is licensed under version 3 of the permissive GNU General Public License"

Please see: http://www.highcharts.com/license

Snorby: https://github.com/Snorby/snorby/blob/master/public/javascripts/highcharts.js

**Comment by DkYSwe** [comment]
Any news on the topic 4 years later? :)
